/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_skill_market_skillMarket_banner_parameter_0$schema = z.object({
  'skillId': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_skill_market_skillMarket_banner_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.union([z.object({
  'code': z.literal("invalid-archive").readonly(),
  'reason': z.union([z.literal("base64"), z.literal("zip")]).readonly(),
}), z.object({
  'code': z.literal("invalid-banner").readonly(),
  'reason': z.union([z.literal("missing"), z.literal("not-regular"), z.literal("path"), z.literal("signature-mismatch"), z.literal("too-large"), z.literal("unsupported-media")]).readonly(),
  'path': z.union([z.string(), z.undefined()]).readonly().optional(),
}), z.object({
  'code': z.literal("invalid-descriptor").readonly(),
  'reason': z.string().readonly(),
  'field': z.union([z.string(), z.undefined()]).readonly().optional(),
}), z.object({
  'code': z.literal("managed-upgrade-required").readonly(),
  'skillId': z.intersection(z.string(), z.unknown()).readonly(),
  'installedVersion': z.union([z.string(), z.undefined()]).readonly().optional(),
  'candidateVersion': z.union([z.string(), z.undefined()]).readonly().optional(),
}), z.object({
  'code': z.literal("manifest-incompatible").readonly(),
  'skillId': z.intersection(z.string(), z.unknown()).readonly(),
  'schemaVersion': z.union([z.number(), z.undefined()]).readonly().optional(),
}), z.object({
  'code': z.literal("not-found").readonly(),
  'skillId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("not-managed").readonly(),
  'skillId': z.intersection(z.string(), z.unknown()).readonly(),
  'reason': z.union([z.literal("malformed-manifest"), z.literal("missing-manifest"), z.literal("name-mismatch")]).readonly(),
}), z.object({
  'code': z.literal("resource-limit").readonly(),
  'limit': z.union([z.literal("archive-bytes"), z.literal("banner-bytes"), z.literal("entry-bytes"), z.literal("file-count"), z.literal("total-bytes")]).readonly(),
  'limitValue': z.number().readonly(),
  'observedValue': z.number().readonly(),
  'entry': z.union([z.string(), z.undefined()]).readonly().optional(),
}), z.object({
  'code': z.literal("unmanaged-conflict").readonly(),
  'skillId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("unsafe-entry").readonly(),
  'entry': z.string().readonly(),
  'reason': z.union([z.literal("duplicate"), z.literal("layout"), z.literal("path"), z.literal("unsupported-type")]).readonly(),
})]).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'skillId': z.intersection(z.string(), z.unknown()).readonly(),
  'mediaType': z.union([z.literal("image/gif"), z.literal("image/jpeg"), z.literal("image/png"), z.literal("image/webp")]).readonly(),
  'dataBase64': z.string().readonly(),
}).readonly(),
})])
const _deepseek_ai_dsh_skill_market_skillMarket_install_parameter_0$schema = z.object({
  'filename': z.string().readonly(),
  'archiveBase64': z.string().readonly(),
  'replaceExisting': z.union([z.literal(false), z.literal(true), z.undefined()]).readonly().optional(),
})
const _deepseek_ai_dsh_skill_market_skillMarket_install_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.union([z.object({
  'code': z.literal("invalid-archive").readonly(),
  'reason': z.union([z.literal("base64"), z.literal("zip")]).readonly(),
}), z.object({
  'code': z.literal("invalid-banner").readonly(),
  'reason': z.union([z.literal("missing"), z.literal("not-regular"), z.literal("path"), z.literal("signature-mismatch"), z.literal("too-large"), z.literal("unsupported-media")]).readonly(),
  'path': z.union([z.string(), z.undefined()]).readonly().optional(),
}), z.object({
  'code': z.literal("invalid-descriptor").readonly(),
  'reason': z.string().readonly(),
  'field': z.union([z.string(), z.undefined()]).readonly().optional(),
}), z.object({
  'code': z.literal("managed-upgrade-required").readonly(),
  'skillId': z.intersection(z.string(), z.unknown()).readonly(),
  'installedVersion': z.union([z.string(), z.undefined()]).readonly().optional(),
  'candidateVersion': z.union([z.string(), z.undefined()]).readonly().optional(),
}), z.object({
  'code': z.literal("manifest-incompatible").readonly(),
  'skillId': z.intersection(z.string(), z.unknown()).readonly(),
  'schemaVersion': z.union([z.number(), z.undefined()]).readonly().optional(),
}), z.object({
  'code': z.literal("not-found").readonly(),
  'skillId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("not-managed").readonly(),
  'skillId': z.intersection(z.string(), z.unknown()).readonly(),
  'reason': z.union([z.literal("malformed-manifest"), z.literal("missing-manifest"), z.literal("name-mismatch")]).readonly(),
}), z.object({
  'code': z.literal("resource-limit").readonly(),
  'limit': z.union([z.literal("archive-bytes"), z.literal("banner-bytes"), z.literal("entry-bytes"), z.literal("file-count"), z.literal("total-bytes")]).readonly(),
  'limitValue': z.number().readonly(),
  'observedValue': z.number().readonly(),
  'entry': z.union([z.string(), z.undefined()]).readonly().optional(),
}), z.object({
  'code': z.literal("unmanaged-conflict").readonly(),
  'skillId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("unsafe-entry").readonly(),
  'entry': z.string().readonly(),
  'reason': z.union([z.literal("duplicate"), z.literal("layout"), z.literal("path"), z.literal("unsupported-type")]).readonly(),
})]).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'skillId': z.intersection(z.string(), z.unknown()).readonly(),
  'operation': z.union([z.literal("installed"), z.literal("upgraded")]).readonly(),
}).readonly(),
})])
const _deepseek_ai_dsh_skill_market_skillMarket_list_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.union([z.object({
  'code': z.literal("invalid-archive").readonly(),
  'reason': z.union([z.literal("base64"), z.literal("zip")]).readonly(),
}), z.object({
  'code': z.literal("invalid-banner").readonly(),
  'reason': z.union([z.literal("missing"), z.literal("not-regular"), z.literal("path"), z.literal("signature-mismatch"), z.literal("too-large"), z.literal("unsupported-media")]).readonly(),
  'path': z.union([z.string(), z.undefined()]).readonly().optional(),
}), z.object({
  'code': z.literal("invalid-descriptor").readonly(),
  'reason': z.string().readonly(),
  'field': z.union([z.string(), z.undefined()]).readonly().optional(),
}), z.object({
  'code': z.literal("managed-upgrade-required").readonly(),
  'skillId': z.intersection(z.string(), z.unknown()).readonly(),
  'installedVersion': z.union([z.string(), z.undefined()]).readonly().optional(),
  'candidateVersion': z.union([z.string(), z.undefined()]).readonly().optional(),
}), z.object({
  'code': z.literal("manifest-incompatible").readonly(),
  'skillId': z.intersection(z.string(), z.unknown()).readonly(),
  'schemaVersion': z.union([z.number(), z.undefined()]).readonly().optional(),
}), z.object({
  'code': z.literal("not-found").readonly(),
  'skillId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("not-managed").readonly(),
  'skillId': z.intersection(z.string(), z.unknown()).readonly(),
  'reason': z.union([z.literal("malformed-manifest"), z.literal("missing-manifest"), z.literal("name-mismatch")]).readonly(),
}), z.object({
  'code': z.literal("resource-limit").readonly(),
  'limit': z.union([z.literal("archive-bytes"), z.literal("banner-bytes"), z.literal("entry-bytes"), z.literal("file-count"), z.literal("total-bytes")]).readonly(),
  'limitValue': z.number().readonly(),
  'observedValue': z.number().readonly(),
  'entry': z.union([z.string(), z.undefined()]).readonly().optional(),
}), z.object({
  'code': z.literal("unmanaged-conflict").readonly(),
  'skillId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("unsafe-entry").readonly(),
  'entry': z.string().readonly(),
  'reason': z.union([z.literal("duplicate"), z.literal("layout"), z.literal("path"), z.literal("unsupported-type")]).readonly(),
})]).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'entries': z.array(z.object({
  'skillId': z.intersection(z.string(), z.unknown()).readonly(),
  'description': z.string().readonly(),
  'version': z.union([z.string(), z.undefined()]).readonly().optional(),
  'author': z.union([z.string(), z.undefined()]).readonly().optional(),
  'tags': z.union([z.array(z.string()), z.undefined()]).readonly().optional(),
  'installedAt': z.number().readonly(),
  'hasBanner': z.boolean().readonly(),
})).readonly(),
}).readonly(),
})])
const _deepseek_ai_dsh_skill_market_skillMarket_uninstall_parameter_0$schema = z.object({
  'skillId': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_skill_market_skillMarket_uninstall_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.union([z.object({
  'code': z.literal("invalid-archive").readonly(),
  'reason': z.union([z.literal("base64"), z.literal("zip")]).readonly(),
}), z.object({
  'code': z.literal("invalid-banner").readonly(),
  'reason': z.union([z.literal("missing"), z.literal("not-regular"), z.literal("path"), z.literal("signature-mismatch"), z.literal("too-large"), z.literal("unsupported-media")]).readonly(),
  'path': z.union([z.string(), z.undefined()]).readonly().optional(),
}), z.object({
  'code': z.literal("invalid-descriptor").readonly(),
  'reason': z.string().readonly(),
  'field': z.union([z.string(), z.undefined()]).readonly().optional(),
}), z.object({
  'code': z.literal("managed-upgrade-required").readonly(),
  'skillId': z.intersection(z.string(), z.unknown()).readonly(),
  'installedVersion': z.union([z.string(), z.undefined()]).readonly().optional(),
  'candidateVersion': z.union([z.string(), z.undefined()]).readonly().optional(),
}), z.object({
  'code': z.literal("manifest-incompatible").readonly(),
  'skillId': z.intersection(z.string(), z.unknown()).readonly(),
  'schemaVersion': z.union([z.number(), z.undefined()]).readonly().optional(),
}), z.object({
  'code': z.literal("not-found").readonly(),
  'skillId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("not-managed").readonly(),
  'skillId': z.intersection(z.string(), z.unknown()).readonly(),
  'reason': z.union([z.literal("malformed-manifest"), z.literal("missing-manifest"), z.literal("name-mismatch")]).readonly(),
}), z.object({
  'code': z.literal("resource-limit").readonly(),
  'limit': z.union([z.literal("archive-bytes"), z.literal("banner-bytes"), z.literal("entry-bytes"), z.literal("file-count"), z.literal("total-bytes")]).readonly(),
  'limitValue': z.number().readonly(),
  'observedValue': z.number().readonly(),
  'entry': z.union([z.string(), z.undefined()]).readonly().optional(),
}), z.object({
  'code': z.literal("unmanaged-conflict").readonly(),
  'skillId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("unsafe-entry").readonly(),
  'entry': z.string().readonly(),
  'reason': z.union([z.literal("duplicate"), z.literal("layout"), z.literal("path"), z.literal("unsupported-type")]).readonly(),
})]).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'skillId': z.intersection(z.string(), z.unknown()).readonly(),
}).readonly(),
})])

export const TYPERT = {
  package: '@deepseek-ai/dsh-skill-market',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-skill-market#skillMarket/banner',
      service: 'skillMarket',
      namespace: 'skillMarket',
      method: 'banner',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-skill-market/types#SkillMarketBannerRequest',
            schema: _deepseek_ai_dsh_skill_market_skillMarket_banner_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-skill-market/types#SkillMarketBannerResult',
        schema: _deepseek_ai_dsh_skill_market_skillMarket_banner_result$schema,
      },
      sourceLocation: {"file":"packages/skill/skill-market/src/index.ts","line":190,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-skill-market#skillMarket/install',
      service: 'skillMarket',
      namespace: 'skillMarket',
      method: 'install',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-skill-market/types#SkillMarketInstallRequest',
            schema: _deepseek_ai_dsh_skill_market_skillMarket_install_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-skill-market/types#SkillMarketInstallResult',
        schema: _deepseek_ai_dsh_skill_market_skillMarket_install_result$schema,
      },
      sourceLocation: {"file":"packages/skill/skill-market/src/index.ts","line":208,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-skill-market#skillMarket/list',
      service: 'skillMarket',
      namespace: 'skillMarket',
      method: 'list',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-skill-market/types#SkillMarketListResult',
        schema: _deepseek_ai_dsh_skill_market_skillMarket_list_result$schema,
      },
      sourceLocation: {"file":"packages/skill/skill-market/src/index.ts","line":229,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-skill-market#skillMarket/uninstall',
      service: 'skillMarket',
      namespace: 'skillMarket',
      method: 'uninstall',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-skill-market/types#SkillMarketUninstallRequest',
            schema: _deepseek_ai_dsh_skill_market_skillMarket_uninstall_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-skill-market/types#SkillMarketUninstallResult',
        schema: _deepseek_ai_dsh_skill_market_skillMarket_uninstall_result$schema,
      },
      sourceLocation: {"file":"packages/skill/skill-market/src/index.ts","line":253,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "description": "Host Remote gateway backed by the marketplace transaction engine. Declared business failures are returned as structured outcomes. Transport, cancellation, and unexpected failures reject. Successful mutations notify the filesystem skill provider only after publication or detachment commits.",
        "summary": "Host Remote gateway backed by the marketplace transaction engine.",
        "tags": [],
        "jsDoc": "/**\n * Host Remote gateway backed by the marketplace transaction engine.\n *\n * Declared business failures are returned as structured outcomes. Transport,\n * cancellation, and unexpected failures reject. Successful mutations notify\n * the filesystem skill provider only after publication or detachment commits.\n */",
        "key": "skillMarket",
        "exportName": "SkillMarketGateway",
        "members": [
          {
            "kind": "method",
            "name": "banner",
            "signature": "@Remote('banner') async banner(request: SkillMarketBannerRequest): Promise<SkillMarketBannerResult>",
            "summary": "Read one installed promotional image.",
            "jsDoc": "/**\n * Read one installed promotional image.\n * @param request - managed skill identity.\n * @returns validated image metadata and bytes, or a declared ownership,\n * compatibility, absence, or image-validation failure.\n */"
          },
          {
            "kind": "method",
            "name": "install",
            "signature": "@Remote('install') async install(request: SkillMarketInstallRequest): Promise<SkillMarketInstallResult>",
            "summary": "Validate and install or upgrade one uploaded marketplace archive.",
            "jsDoc": "/**\n * Validate and install or upgrade one uploaded marketplace archive.\n * @param request - uploaded archive and explicit replacement intent.\n * @returns committed installation facts, or a declared validation,\n * ownership, compatibility, or replacement-confirmation failure.\n */"
          },
          {
            "kind": "method",
            "name": "list",
            "signature": "@Remote('list') async list(): Promise<SkillMarketListResult>",
            "summary": "List managed marketplace installations.",
            "jsDoc": "/**\n * List managed marketplace installations.\n * @returns deterministic managed inventory, or a declared domain failure.\n */"
          },
          {
            "kind": "method",
            "name": "uninstall",
            "signature": "@Remote('uninstall') async uninstall(request: SkillMarketUninstallRequest): Promise<SkillMarketUninstallResult>",
            "summary": "Remove one managed marketplace installation.",
            "jsDoc": "/**\n * Remove one managed marketplace installation.\n * @param request - managed skill identity.\n * @returns detached installation facts, or a declared ownership,\n * compatibility, or absence failure.\n */"
          }
        ],
        "types": [
          {
            "name": "Branded",
            "declaration": "export type Branded<B extends string> = string & { readonly [BRAND]: B; };"
          },
          {
            "name": "SkillMarketBannerMediaType",
            "declaration": "export type SkillMarketBannerMediaType = 'image/png' | 'image/jpeg' | 'image/webp' | 'image/gif';"
          },
          {
            "name": "SkillMarketBannerRequest",
            "declaration": "export interface SkillMarketBannerRequest {\n    readonly skillId: SkillMarketSkillId;\n}"
          },
          {
            "name": "SkillMarketBannerResult",
            "declaration": "export type SkillMarketBannerResult = SkillMarketResult<SkillMarketBannerValue>;"
          },
          {
            "name": "SkillMarketBannerValue",
            "declaration": "export interface SkillMarketBannerValue {\n    readonly skillId: SkillMarketSkillId;\n    readonly mediaType: SkillMarketBannerMediaType;\n    readonly dataBase64: string;\n}"
          },
          {
            "name": "SkillMarketEntry",
            "declaration": "export interface SkillMarketEntry {\n    readonly skillId: SkillMarketSkillId;\n    readonly description: string;\n    readonly version?: string | undefined;\n    readonly author?: string | undefined;\n    readonly tags?: readonly string[] | undefined;\n    readonly installedAt: number;\n    readonly hasBanner: boolean;\n}"
          },
          {
            "name": "SkillMarketFailure",
            "declaration": "export type SkillMarketFailure = SkillMarketInvalidArchiveFailure | SkillMarketResourceLimitFailure | SkillMarketUnsafeEntryFailure | SkillMarketInvalidDescriptorFailure | SkillMarketInvalidBannerFailure | SkillMarketManagedUpgradeRequiredFailure | SkillMarketUnmanagedConflictFailure | SkillMarketManifestIncompatibleFailure | SkillMarketNotFoundFailure | SkillMarketNotManagedFailure;"
          },
          {
            "name": "SkillMarketInstallRequest",
            "declaration": "export interface SkillMarketInstallRequest {\n    readonly filename: string;\n    readonly archiveBase64: string;\n    readonly replaceExisting?: boolean | undefined;\n}"
          },
          {
            "name": "SkillMarketInstallResult",
            "declaration": "export type SkillMarketInstallResult = SkillMarketResult<SkillMarketInstallValue>;"
          },
          {
            "name": "SkillMarketInstallValue",
            "declaration": "export interface SkillMarketInstallValue {\n    readonly skillId: SkillMarketSkillId;\n    readonly operation: 'installed' | 'upgraded';\n}"
          },
          {
            "name": "SkillMarketInvalidArchiveFailure",
            "declaration": "export interface SkillMarketInvalidArchiveFailure {\n    readonly code: 'invalid-archive';\n    readonly reason: 'base64' | 'zip';\n}"
          },
          {
            "name": "SkillMarketInvalidBannerFailure",
            "declaration": "export interface SkillMarketInvalidBannerFailure {\n    readonly code: 'invalid-banner';\n    readonly reason: 'path' | 'missing' | 'not-regular' | 'unsupported-media' | 'signature-mismatch' | 'too-large';\n    readonly path?: string | undefined;\n}"
          },
          {
            "name": "SkillMarketInvalidDescriptorFailure",
            "declaration": "export interface SkillMarketInvalidDescriptorFailure {\n    readonly code: 'invalid-descriptor';\n    readonly reason: string;\n    readonly field?: string | undefined;\n}"
          },
          {
            "name": "SkillMarketListResult",
            "declaration": "export type SkillMarketListResult = SkillMarketResult<SkillMarketListValue>;"
          },
          {
            "name": "SkillMarketListValue",
            "declaration": "export interface SkillMarketListValue {\n    readonly entries: readonly SkillMarketEntry[];\n}"
          },
          {
            "name": "SkillMarketManagedUpgradeRequiredFailure",
            "declaration": "export interface SkillMarketManagedUpgradeRequiredFailure {\n    readonly code: 'managed-upgrade-required';\n    readonly skillId: SkillMarketSkillId;\n    readonly installedVersion?: string | undefined;\n    readonly candidateVersion?: string | undefined;\n}"
          },
          {
            "name": "SkillMarketManifestIncompatibleFailure",
            "declaration": "export interface SkillMarketManifestIncompatibleFailure {\n    readonly code: 'manifest-incompatible';\n    readonly skillId: SkillMarketSkillId;\n    readonly schemaVersion?: number | undefined;\n}"
          },
          {
            "name": "SkillMarketNotFoundFailure",
            "declaration": "export interface SkillMarketNotFoundFailure {\n    readonly code: 'not-found';\n    readonly skillId: SkillMarketSkillId;\n}"
          },
          {
            "name": "SkillMarketNotManagedFailure",
            "declaration": "export interface SkillMarketNotManagedFailure {\n    readonly code: 'not-managed';\n    readonly skillId: SkillMarketSkillId;\n    readonly reason: 'missing-manifest' | 'malformed-manifest' | 'name-mismatch';\n}"
          },
          {
            "name": "SkillMarketResourceLimitFailure",
            "declaration": "export interface SkillMarketResourceLimitFailure {\n    readonly code: 'resource-limit';\n    readonly limit: 'archive-bytes' | 'file-count' | 'entry-bytes' | 'total-bytes' | 'banner-bytes';\n    readonly limitValue: number;\n    readonly observedValue: number;\n    readonly entry?: string | undefined;\n}"
          },
          {
            "name": "SkillMarketResult",
            "declaration": "export type SkillMarketResult<Value> = { readonly ok: true; readonly value: Value; } | { readonly ok: false; readonly error: SkillMarketFailure; };"
          },
          {
            "name": "SkillMarketSkillId",
            "declaration": "export type SkillMarketSkillId = Branded<'SkillMarketSkillId'>;"
          },
          {
            "name": "SkillMarketUninstallRequest",
            "declaration": "export interface SkillMarketUninstallRequest {\n    readonly skillId: SkillMarketSkillId;\n}"
          },
          {
            "name": "SkillMarketUninstallResult",
            "declaration": "export type SkillMarketUninstallResult = SkillMarketResult<SkillMarketUninstallValue>;"
          },
          {
            "name": "SkillMarketUninstallValue",
            "declaration": "export interface SkillMarketUninstallValue {\n    readonly skillId: SkillMarketSkillId;\n}"
          },
          {
            "name": "SkillMarketUnmanagedConflictFailure",
            "declaration": "export interface SkillMarketUnmanagedConflictFailure {\n    readonly code: 'unmanaged-conflict';\n    readonly skillId: SkillMarketSkillId;\n}"
          },
          {
            "name": "SkillMarketUnsafeEntryFailure",
            "declaration": "export interface SkillMarketUnsafeEntryFailure {\n    readonly code: 'unsafe-entry';\n    readonly entry: string;\n    readonly reason: 'path' | 'duplicate' | 'unsupported-type' | 'layout';\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
