/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { SkillMarketBannerRequest, SkillMarketBannerResult, SkillMarketInstallRequest, SkillMarketInstallResult, SkillMarketListResult, SkillMarketUninstallRequest, SkillMarketUninstallResult } from '@deepseek-ai/dsh-skill-market/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$736b696c6c4d61726b6574 {
    banner: (request: SkillMarketBannerRequest) => Promise<RemoteResult<SkillMarketBannerResult>>
    install: (request: SkillMarketInstallRequest) => Promise<RemoteResult<SkillMarketInstallResult>>
    list: () => Promise<RemoteResult<SkillMarketListResult>>
    uninstall: (request: SkillMarketUninstallRequest) => Promise<RemoteResult<SkillMarketUninstallResult>>
  }
  interface TypertRemoteMap {
    'skillMarket/banner': (request: SkillMarketBannerRequest) => Promise<RemoteResult<SkillMarketBannerResult>>
    'skillMarket/install': (request: SkillMarketInstallRequest) => Promise<RemoteResult<SkillMarketInstallResult>>
    'skillMarket/list': () => Promise<RemoteResult<SkillMarketListResult>>
    'skillMarket/uninstall': (request: SkillMarketUninstallRequest) => Promise<RemoteResult<SkillMarketUninstallResult>>
  }
  interface TypertRemoteNamespaceMap {
    'skillMarket': TypertRemoteNamespace$736b696c6c4d61726b6574
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
